
#ifndef DEFINES_H
#define DEFINES_H

	#define JPOSX 1000
	#define JPOSY 1000

	#define JTAMX 1000
	#define JTAMY 1000

	#define AQUILES_X 80
	#define AQUILES_Y 350

	#define ALTURA_PULO 600
	#define INCREMENTO_PULO 18

	#define ALTURA_MINIMA_CANCELA_PULO 400

	#define AQUILES_LARG 100
	#define AQUILES_ALT 100

	#define PERIODO 33

	#define VELOCIDADE_AQUILES 2
	#define DELAY_PULO 1
	#define DELAY_RECUPERACAO 10

	#define VELOCIDADE_FUNDO 4

	#define DISTANCIA_FASE 1000
	#define DISTANCIA_COMECO 100

	#define INIMIGOS_FASE_1 20

	#define ARVORE_Y 380

	#define ARVORE_LARG 100
	#define ARVORE_ALT 135

	#define ARBUSTO_Y 360

	#define ARBUSTO_LARG 135
	#define ARBUSTO_ALT 135

	#define PEDRA_Y 320

	#define PEDRA_LARG 100
	#define PEDRA_ALT 100

	#define LARG_HITBOX 10

	#define VELOCIDADE_INIMIGO 10

	#define X_MIN_INIMIGO 0
	#define X_MAX_INIMIGO 100

	#define OFFSET_ALTURA 370
	#define OFFSET_LARGURA 10

	#define DISTANCIA_MINIMA 25

	#define ESCALA 150

#endif