
#ifndef DEFINES_H
#define DEFINES_H

	#define JPOSX 1000
	#define JPOSY 1000

	#define JTAMX 1000
	#define JTAMY 1000

	#define AQUILES_X 80
	#define AQUILES_Y 350

	#define BOSS_Y 350

	#define BOSS_LARG 100
	#define BOSS_ALT 100

	#define ALTURA_PULO 600
	#define INCREMENTO_PULO 18

	#define ALTURA_MINIMA_CANCELA_PULO 400

	#define AQUILES_LARG 100
	#define AQUILES_ALT 100

	#define PERIODO 33

	#define VELOCIDADE_AQUILES 2
	#define DELAY_PULO 1
	#define DELAY_TIRO 4
	#define DELAY_TIRO_INIMIGO 5
	#define DELAY_RECUPERACAO 10

	#define VELOCIDADE_FUNDO 4

	#define DISTANCIA_FASE 1000
	#define DISTANCIA_FINAL 2000
	#define DISTANCIA_COMECO 100

	#define OFFSET_BOSS 850

	#define TEMPO_INTRODUCAO 20
	#define INCREMENTO_INTRODUCAO 10

	#define INIMIGOS_FASE_1 20
	#define QUANTIDADE_BOSS 1

	#define ARVORE_Y 380

	#define ARVORE_LARG 100
	#define ARVORE_ALT 135

	#define ARBUSTO_Y 360

	#define ARBUSTO_LARG 135
	#define ARBUSTO_ALT 135

	#define PEDRA_Y 320

	#define PEDRA_LARG 100
	#define PEDRA_ALT 100

	#define LARG_HITBOX 10

	#define VELOCIDADE_INIMIGO 10

	#define X_MIN_INIMIGO 0
	#define X_MAX_INIMIGO 100

	#define OFFSET_ALTURA 370
	#define OFFSET_LARGURA 10

	#define DISTANCIA_MINIMA 25

	#define DISTANCIA_INICIAL 0

	#define ESCALA 150

	#define INICIO_TIRO 150
	#define VELOCIDADE_TIRO 20
	#define FIM_TIRO 1000

	#define COLISAO 1												// MUDAR PARA 0 PARA DESLIGAR A COLISÃO

	#define QUANTIDADE_VIDA_BOSS 5

	#define DELAY_MORTE_BOSS 4
	#define DELAY_MORTE_BOSS_FINAL 15

	#define DELAY_VELOCIDADE_BOSS 1

	#define MENSAGEM_GO_X 500
	#define MENSAGEM_GO_Y 630

	#define MENSAGEM_LARG 800
	#define MENSAGEM_ALT 80

	#define MENSAGEM_VIT_LARG 400
	#define MENSAGEM_VIT_ALT 80

	#define MENSAGEM_VIT_X 500
	#define MENSAGEM_VIT_Y 630

	#define MENSAGEM_GO2_X 500	
	#define MENSAGEM_GO2_Y 550

#endif